### ISSUE TITLE
Publish to Gradle Plugin Portal

### ISSUE THREAD

**Issue by triphora** [dexman545/Outlet#1]
Hi!

I think this plugin is quite neat and would like to use it for myself.

However, I am not too much of a fan of Jitpack, and I do not trust it not to break arbitrarily when I want to build my projects.

Could you publish this to the [Gradle Plugin Portal](https://plugins.gradle.org)? An example setup that has publishing to the Portal can be found on [Minotaur](https://github.com/modrinth/minotaur/blob/master/build.gradle).

Thanks!

**Comment by dexman545** [comment]
We'll see if it gets approved or not.

**Comment by dexman545** [comment]
Now available on the plugin portal
https://plugins.gradle.org/plugin/io.github.dexman545.outlet

**Comment by triphora** [comment]
Thanks!
