### ISSUE TITLE
Incorrect Fabric API version

### ISSUE THREAD

**Issue by OffsetMonkey538** [dexman545/Outlet#2]
Running
```gradle
print(outlet.fapiVersion("1.20.1"))
```
prints out
```
0.87.0+1.20.2
```
Which doesn't work for 1.20.1

**Comment by dexman545** [comment]
This is a quick fix, probably will have some issues on snapshots or automatically updating to a next compatible fapi version, but those seem to be rare now given how MC is behaving.

**Comment by OffsetMonkey538** [comment]
Seems to be happening again :(

**Comment by dexman545** [comment]
Versions?

**Comment by OffsetMonkey538** [comment]
Supposed to be like 0.87.0+1.20.1, but gave me 0.87.2+1.20.2
Could it be choosing the latest fapi version, but isn't checking if it works for the version?

**Comment by dexman545** [comment]
I cannot reproduce this. Please make sure you are using Outlet 1.6.1. Also check the mc version range you gave it, if the range allows 1.20.2, the fapi pull will get versions for it unless you manually specify the mc version for fapi.

Also note outlet caches the versions, so you may need to invalidate/remove it.

**Comment by OffsetMonkey538** [comment]
Ah, I might not have the latest version of outlet. I'll check once I get back home

**Comment by OffsetMonkey538** [comment]
Ah yeah, seems like I was using an old version of outlet.

**Comment by OffsetMonkey538** [comment]
Using outlet 1.6.1 and it's giving me fapi `0.91.4+1.20.5` instead of `0.91.2+1.20.2` for `print(outlet.fapiVersion("1.20.2"))`. For `1.20.3` and `1.20.4` it gives the correct versions. Is there another update or something?

**Comment by dexman545** [comment]
1.6.1 is the latest.

I cannot reproduce this, please try clearing the outlet cache.

**Comment by OffsetMonkey538** [comment]
I'm pretty sure I tried cleared the cache at least a few times yesterday and it was still the same. I have no idea but today it seems to work. Christmas miracle I guess??
